- name: Copy Job file 
  ansible.builtin.template: 
    src:  mbranch.xml
    dest: /tmp/mbranch.xml

- name: Create a jenkins job using basic authentication 
  community.general.jenkins_job: 
    config: "{{lookup('file','/tmp/mbranch.xml')}}"
    name: "{{item.jobName}}"
    password: "{{secrets.admin_password}}"
    url: "http://jenkins-internal.rdevops.online:8080"
    user: "{{secrets.admin_user}}"